controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder
      - arm
      - forearm
      - roll_spindle
      - pitch_spindle
      - yaw_spindle
initial:  # Define initial robot poses.
  - group: arm
    pose: init_pose