# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: init_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder
    - arm
    - forearm
    - roll_spindle
    - pitch_spindle
    - yaw_spindle
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: effort_controllers/JointPositionController
  joints:
    - shoulder
    - arm
    - forearm
    - roll_spindle
    - pitch_spindle
    - yaw_spindle
  gains:
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    roll_spindle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pitch_spindle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaw_spindle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1