Total: 21
EffectorLength: 0.05
Points:
  -
    tag: pre_place #准备放入矿仓
    id: 0
    xyz:
      - -0.14
      - -0.01
      - 0.67
    rpy: 
      - 2.0601
      - -0.0044
      - 1.6252
    action: 1
  -
    tag: pre_pick_island #准备抓取矿石(原姿态，现已废弃)
    id: 1
    xyz:
      - 0.28
      - 0.00
      - 0.61
    rpy:
      - 2.8735
      - -0.0014
      - -1.5768
    action: 1
  -
    tag: place #放入矿仓
    id: 2
    xyz:
      - -0.262
      - 0
      - 0.60
    rpy: 
      - 1.7653
      - -0.0054
      - 1.6255
    action: 1
  -
    tag: pick_island #手动抓取矿石
    id: 3
    xyz:
      - 0.515
      - 0.00
      - 0.54
    rpy:
      - 3.05
      - 0
      - -1.57
    action: 1
  -
    tag: pick_up #抓取完矿石后的抬高
    id: 4
    xyz:
      - 0.41
      - 0.00
      - 0.79
    rpy:
      - -2.1234
      - -0.0011
      - -1.5708
    action: 1
  -
    tag: pre_pick_block #准备抓取障碍块
    id: 5
    xyz:
      - 0.28
      - -0.00
      - 0.61
    rpy:
      - 2.5145
      - -0.0033
      - -1.5751
    action: 1
  -
    tag: pick_block #抓取障碍块
    id: 6
    xyz:
      - 0.56
      - -0.00
      - 0.26
    rpy:
      - 2.5896
      - -0.0044
      - -1.5773
    action: 1
  -
    tag: pick_front1 #障碍块放置前端
    id: 7
    xyz:
      - 0.30
      - 0.00
      - 0.45
    rpy:
      - 2.1951
      - -0.0073
      - -1.5743
    action: 1
  -
    tag: pick_front2 #障碍块放置前端
    id: 8
    xyz:
      - 0.31
      - 0.00
      - 0.42
    rpy:
      - 2.3777
      - -0.0055
      - -1.5751
    action: 1
  -
    tag: pick_mineral #抓取已放置的障碍块
    id: 9
    xyz:
      - -0.16
      - -0.01
      - 0.57
    rpy:
      - 1.9285
      - -0.0000
      - 1.6220
    action: 1
  -
    tag: pre_exchange #准备兑换矿石
    id: 10
    xyz:
      - 0.27
      - 0.00
      - 0.83
    rpy:
      - -2.8374
      - -0.0052
      - -1.5715
    action: 1
  -
    tag: exchange #兑换矿石
    id: 11
    xyz:
      - 0.34
      - -0.00
      - 0.72
    rpy:
      - -3.0897
      - 0.0001
      - -1.5767
    action: 1
  -
    tag: pre_pick_island2 #准备抓取矿石(最前姿态)
    id: 12
    xyz:
      - 0.43
      - 0.00
      - 0.54
    rpy:
      - 3.05
      - 0.0000
      - -1.57
    action: 1
  -
    tag: drive #开车姿态
    id: 13
    xyz:
      - 0.10
      - -0.15
      - 0.56
    rpy:
      - 3.1336
      - -0.0000
      - -3.0982
    action: 1
  -
    tag: pre_exchange2 #矿石位姿不对的时候转一转
    id: 14
    xyz:
      - 0.27
      - 0.00
      - 0.83
    rpy:
      - -0.3166
      - -0.0013
      - 1.5667
    action: 1
  -
    tag: exchange2 #转完之后的兑换
    id: 15
    xyz:
      - 0.34
      - 0.00
      - 0.72
    rpy:
      - -0.0632
      - 0.0003
      - 1.5765
    action: 1
  -
    tag: boxing_right  #拳击姿态右
    id: 16
    xyz:
      - 0.49
      - -0.15
      - 0.55
    rpy:
      - 3.1212
      - 0.0000
      - -1.9443
    action: 1
  -
    tag: boxing_middle #拳击姿态中
    id: 17
    xyz:
      - 0.49
      - 0.00
      - 0.55
    rpy:
      - 3.12
      - 0.0000
      - -1.57
    action: 1
  -
    tag: boxing_left #拳击姿态左
    id: 18
    xyz:
      - 0.48
      - 0.15
      - 0.55
    rpy:
      - 3.12
      - 0.0000
      - -1.57
    action: 1
  -
    tag: zero_point #零点
    id: 19
    xyz:
      - 0.38
      - 0.00
      - 0.62
    rpy:
      - 3.1416
      - 0.0000
      - -1.5708
    action: 1
  -
    tag: temp_point #抓取中间点
    id: 20
    xyz:
      - 0.49
      - 0.00
      - 0.54
    rpy:
      - 3.05
      - 0.0000
      - -1.57
    action: 1
